import './global.css';
import {globalTopic, subscribe} from '@enegix/events';

export const metadata = {
  title: 'Welcome to next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(globalTopic.metadata);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
